CREATE OR REPLACE PROCEDURE brh.insere_projeto
    (p_NOME_DO_PROJETO IN VARCHAR2, p_RESPONSAVEL_DO_PROJETO IN VARCHAR2)
IS
BEGIN
    INSERT INTO brh.projeto (ID_PROJETO, NOME_DO_PROJETO, RESPONSAVEL_DO_PROJETO)
    VALUES (brh.seq_projeto.NEXTVAL, p_NOME_DO_PROJETO, p_RESPONSAVEL_DO_PROJETO)
END;
